import 'package:flutter/material.dart';
import 'package:quiver/strings.dart';

class UploadPdf extends StatefulWidget {
  static const route = '/uploadPdf';
  @override
  _UploadPdfState createState() => _UploadPdfState();
}

class _UploadPdfState extends State<UploadPdf> {
  bool hideText = true;
  bool touched = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).backgroundColor,
          title: Text('Upload NSDL or CDSL '),
        ),
        body: Scrollbar(
            child: ListView(
                physics: BouncingScrollPhysics(),
                shrinkWrap: true,
                padding: EdgeInsets.all(8.0),
                children: <Widget>[
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Text(
                    'We Support NSDL and CDSL consolidated PDF statements generated by CAMS, '),
              ),
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Text('Please Upload PDF Statement along with Password'),
              ),
              Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: FlatButton(
                    child: Text(
                      "Select File",
                      style: TextStyle(fontSize: 15),
                    ),
                    onPressed: () {},
                  )),
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: TextFormField(
                  key: ValueKey("Pdf Password"),
                  maxLines: 1,
                  obscureText: hideText,
                  autofocus: false,
                  onChanged: (String value) => setState(() {
                    this.touched = isNotEmpty(value);
                  }),
                  validator: (value) => _validatePassword(value),
                  //onSaved: (value) => widget.onSaved(value),
                  decoration: touched
                      ? InputDecoration(
                          suffixIcon: InkWell(
                            child: Icon(
                              Icons.remove_red_eye,
                              color: hideText ? Colors.grey : Colors.blue,
                            ),
                            onTap: () => setState(() {
                              this.hideText = !hideText;
                            }),
                          ),
                        )
                      : null,
                ),
              ),
              Padding(
                padding: EdgeInsets.all(16.0),
                child: FlatButton(
                  child: Text(
                    'Upload',
                    style: TextStyle(fontSize: 15),
                  ),
                  onPressed: () {},
                ),
              )
            ])));
  }

  String _validatePassword(String password) {
    if (password.isEmpty) {
      return "Password field cannot be empty";
    } else if (password.length < 6) {
      return "Password should contain at least 6 symbols";
    }
    return null;
  }
}
